# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ре:форма
email: reformarf@bk.ru
description: Ассоциация по содействию в социально-культурном и экологическом развитии общества "Ре:форма"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://Re-forma.github.io" # the base hostname & protocol for your site, e.g. http://example.com

vk_username: yar_ecomobile
facebook_username: Yar.ecomobile
github_username: Re-forma
instagram_username: yar_ecomobile
youtube_username: UCUUmJzcOR_5Nd_QynTNLMEA

# Build settings
incremental: true
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-asciidoc

header_pages:
  - yar-ecomobile.adoc
  - children.adoc
  - picnics.adoc

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - README.adoc
